
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Docdbnum_Service", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.6.28/ipphdataservice/docdbnum_service.asmx?wsdl")
public class DocdbnumService
    extends Service
{

    private final static URL DOCDBNUMSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCDBNUMSERVICE_EXCEPTION;
    private final static QName DOCDBNUMSERVICE_QNAME = new QName("http://tempuri.org/", "Docdbnum_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.6.28/ipphdataservice/docdbnum_service.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCDBNUMSERVICE_WSDL_LOCATION = url;
        DOCDBNUMSERVICE_EXCEPTION = e;
    }

    public DocdbnumService() {
        super(__getWsdlLocation(), DOCDBNUMSERVICE_QNAME);
    }

    public DocdbnumService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCDBNUMSERVICE_QNAME, features);
    }

    public DocdbnumService(URL wsdlLocation) {
        super(wsdlLocation, DOCDBNUMSERVICE_QNAME);
    }

    public DocdbnumService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCDBNUMSERVICE_QNAME, features);
    }

    public DocdbnumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocdbnumService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocdbnumServiceSoap
     */
    @WebEndpoint(name = "Docdbnum_ServiceSoap")
    public DocdbnumServiceSoap getDocdbnumServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "Docdbnum_ServiceSoap"), DocdbnumServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocdbnumServiceSoap
     */
    @WebEndpoint(name = "Docdbnum_ServiceSoap")
    public DocdbnumServiceSoap getDocdbnumServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "Docdbnum_ServiceSoap"), DocdbnumServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DocdbnumServiceSoap
     */
    @WebEndpoint(name = "Docdbnum_ServiceSoap12")
    public DocdbnumServiceSoap getDocdbnumServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "Docdbnum_ServiceSoap12"), DocdbnumServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocdbnumServiceSoap
     */
    @WebEndpoint(name = "Docdbnum_ServiceSoap12")
    public DocdbnumServiceSoap getDocdbnumServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "Docdbnum_ServiceSoap12"), DocdbnumServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCDBNUMSERVICE_EXCEPTION!= null) {
            throw DOCDBNUMSERVICE_EXCEPTION;
        }
        return DOCDBNUMSERVICE_WSDL_LOCATION;
    }

}
