
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Docdbnum_ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocdbnumServiceSoap {


    /**
     * 
     * @param docdbPubCountry
     * @param docdbPubKind
     * @param docdbPubNum
     * @return
     *     returns org.tempuri.DocResult
     */
    @WebMethod(operationName = "GetStdPublicationInfo", action = "http://tempuri.org/GetStdPublicationInfo")
    @WebResult(name = "GetStdPublicationInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStdPublicationInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStdPublicationInfo")
    @ResponseWrapper(localName = "GetStdPublicationInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStdPublicationInfoResponse")
    public DocResult getStdPublicationInfo(
        @WebParam(name = "docdb_pub_country", targetNamespace = "http://tempuri.org/")
        String docdbPubCountry,
        @WebParam(name = "docdb_pub_num", targetNamespace = "http://tempuri.org/")
        String docdbPubNum,
        @WebParam(name = "docdb_pub_kind", targetNamespace = "http://tempuri.org/")
        String docdbPubKind);

    /**
     * 
     * @param docdbAppNum
     * @param docdbAppKind
     * @param docdbAppCountry
     * @return
     *     returns org.tempuri.DocResult
     */
    @WebMethod(operationName = "GetStdApplicationInfo", action = "http://tempuri.org/GetStdApplicationInfo")
    @WebResult(name = "GetStdApplicationInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStdApplicationInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStdApplicationInfo")
    @ResponseWrapper(localName = "GetStdApplicationInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStdApplicationInfoResponse")
    public DocResult getStdApplicationInfo(
        @WebParam(name = "docdb_app_country", targetNamespace = "http://tempuri.org/")
        String docdbAppCountry,
        @WebParam(name = "docdb_app_num", targetNamespace = "http://tempuri.org/")
        String docdbAppNum,
        @WebParam(name = "docdb_app_kind", targetNamespace = "http://tempuri.org/")
        String docdbAppKind);

    /**
     * 
     * @param isLike
     * @param numType
     * @param number
     * @param kind
     * @param country
     * @return
     *     returns org.tempuri.DocResult
     */
    @WebMethod(operationName = "GetStdAppPubInfo", action = "http://tempuri.org/GetStdAppPubInfo")
    @WebResult(name = "GetStdAppPubInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStdAppPubInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStdAppPubInfo")
    @ResponseWrapper(localName = "GetStdAppPubInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStdAppPubInfoResponse")
    public DocResult getStdAppPubInfo(
        @WebParam(name = "country", targetNamespace = "http://tempuri.org/")
        String country,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "kind", targetNamespace = "http://tempuri.org/")
        String kind,
        @WebParam(name = "numType", targetNamespace = "http://tempuri.org/")
        int numType,
        @WebParam(name = "isLike", targetNamespace = "http://tempuri.org/")
        boolean isLike);

    /**
     * 
     * @param isLike
     * @param numType
     * @param number
     * @param date
     * @param kind
     * @param country
     * @return
     *     returns org.tempuri.DocResult
     */
    @WebMethod(operationName = "GetStdAppPubInfo2", action = "http://tempuri.org/GetStdAppPubInfo2")
    @WebResult(name = "GetStdAppPubInfo2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStdAppPubInfo2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStdAppPubInfo2")
    @ResponseWrapper(localName = "GetStdAppPubInfo2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStdAppPubInfo2Response")
    public DocResult getStdAppPubInfo2(
        @WebParam(name = "country", targetNamespace = "http://tempuri.org/")
        String country,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "kind", targetNamespace = "http://tempuri.org/")
        String kind,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date,
        @WebParam(name = "numType", targetNamespace = "http://tempuri.org/")
        int numType,
        @WebParam(name = "isLike", targetNamespace = "http://tempuri.org/")
        boolean isLike);

}
